/**
 * store/gameLogicStore.ts
 * =============================================================================
 * Zustand store for the in-progress game engine state.
 *
 * Responsibilities:
 *  - Holds the authoritative in-memory state of a single match.
 *  - Delegates ALL rule evaluation to `lib/caidaRules.ts` (pure functions).
 *  - Exposes a single high-level action: `playCard(playerId, card)`.
 *  - Manages round lifecycle: deal → play → score → next round / game over.
 *
 * This store is NOT persisted to localStorage — the Supabase Realtime channel
 * (managed by `hooks/useCaidaEngine.ts`) is the source of truth for recovery.
 * =============================================================================
 */

import { create } from "zustand";
import {
    generateDeck,
    shuffleDeck,
    dealCards,
    calculateCapture,
    checkCaida,
    detectCantos,
    calculatePoints,
    resolveMayorCartas,
    checkWinCondition,
} from "@/lib/caidaRules";
import type {
    Card,
    EnginePlayer,
    EngineState,
    LastPlay,
    PointEvent,
    RoundPhase,
} from "@/types/caida.types";

// ---------------------------------------------------------------------------
// Store interface
// ---------------------------------------------------------------------------

export interface GameLogicStore extends EngineState {
    // ── Initialisation ──────────────────────────────────────────────────────
    /**
     * Starts a brand-new game.
     * @param playerIds  Ordered array of player IDs (index 0 goes first).
     * @param predefinedDeck Optional pre-shuffled deck to ensure sync across clients.
     */
    initGame: (playerIds: string[], predefinedDeck?: Card[], initialDealerId?: string) => void;

    // ── Round lifecycle ──────────────────────────────────────────────────────
    /**
     * Deals a new round: 3 cards to each player, 4 face-up on the table.
     * Safe to call only when `deck` has enough cards; throws otherwise.
     */
    dealRound: () => void;

    // ── Core action ─────────────────────────────────────────────────────────
    /**
     * A player plays a card from their hand.
     *
     * Validates:
     *  - The game is in "playing" phase.
     *  - It is the player's turn.
     *  - The player actually holds the card.
     *
     * Then applies capture logic, detects Caída / Limpieza, advances the turn,
     * and transitions the phase when all hands are empty.
     *
     * @param playerId  The acting player's ID.
     * @param card      The card being played (must be in the player's hand).
     * @returns         An array of PointEvents generated by the play (may be empty).
     * @throws          Error on invalid play attempt.
     */
    playCard: (playerId: string, card: Card) => PointEvent[];

    /**
     * Tallies end-of-round points (mayorCartas) and either starts the next
     * round or ends the game.
     */
    scoreRound: () => void;

    // ── Utilities ────────────────────────────────────────────────────────────
    /** Full reset — use when navigating away from the table. */
    resetEngine: () => void;
}

// ---------------------------------------------------------------------------
// Initial state
// ---------------------------------------------------------------------------

const INITIAL_STATE: EngineState = {
    deck: [],
    tableCards: [],
    players: [],
    currentTurn: null,
    lastPlay: null,
    round: 0,
    phase: "idle",
    winnerId: null,
    dealerId: null,
};

// ---------------------------------------------------------------------------
// Helper: build a fresh EnginePlayer
// ---------------------------------------------------------------------------
function makePlayer(id: string): EnginePlayer {
    return { id, hand: [], captured: [], score: 0, cantos: [] };
}

// ---------------------------------------------------------------------------
// Store implementation
// ---------------------------------------------------------------------------

export const useGameLogicStore = create<GameLogicStore>()((set, get) => ({
    // Spread initial state
    ...INITIAL_STATE,

    // ── initGame ──────────────────────────────────────────────────────────────
    initGame(
        playerIds: string[],
        predefinedDeck?: Card[],
        initialDealerId?: string,
    ) {
        if (playerIds.length < 2) {
            throw new Error("Caída requires at least 2 players.");
        }

        const players = playerIds.map(makePlayer);
        const deck = predefinedDeck ?? shuffleDeck(generateDeck());
        const dealerId =
            initialDealerId ??
            playerIds[Math.floor(Math.random() * playerIds.length)];

        set({
            ...INITIAL_STATE,
            deck,
            players,
            phase: "dealing",
            round: 0,
            dealerId,
        });

        // Immediately deal the first round
        get().dealRound();
    },

    // ── dealRound ─────────────────────────────────────────────────────────────
    dealRound() {
        const { deck, players, dealerId, round } = get();

        const isNewDeck = round === 0;
        const cardsNeeded = players.length * 3 + (isNewDeck ? 4 : 0);

        if (deck.length < cardsNeeded) {
            throw new RangeError(
                `Not enough cards to deal a new round. Need ${cardsNeeded}, have ${deck.length}.`,
            );
        }

        let remaining = [...deck];
        const updatedPlayers: EnginePlayer[] = [];

        let highestCantoPlayerId: string | null = null;
        let highestCantoValue = 0;

        for (const player of players) {
            const { dealt, remaining: rest } = dealCards(remaining, 3);
            remaining = rest;
            const cantos = detectCantos(dealt);

            if (cantos.length > 0) {
                const cantoPoints = calculatePoints({
                    type: "canto",
                    forPlayerId: player.id,
                    canto: cantos[0],
                });
                if (cantoPoints > highestCantoValue) {
                    highestCantoValue = cantoPoints;
                    highestCantoPlayerId = player.id;
                }
            }

            updatedPlayers.push({
                ...player,
                hand: dealt,
                cantos,
            });
        }

        // Apply points for the highest canto
        let instantWinnerId: string | null = null;
        if (highestCantoPlayerId && highestCantoValue > 0) {
            const idx = updatedPlayers.findIndex(
                (p) => p.id === highestCantoPlayerId,
            );
            if (idx !== -1) {
                updatedPlayers[idx].score += highestCantoValue;
                if (highestCantoValue === 24 || updatedPlayers[idx].score >= 24) {
                    instantWinnerId = highestCantoPlayerId;
                }
            }
        }

        // Deal 4 cards face-up to the table ONLY on a new deck (la sopa)
        let newTableCards = [...get().tableCards];
        if (isNewDeck) {
            newTableCards = [];
            while (newTableCards.length < 4) {
                if (remaining.length === 0) break;
                const candidate = remaining.shift()!;
                if (newTableCards.some((c) => c.value === candidate.value)) {
                    // Duplicate value found, put it back at the end of the remaining deck
                    remaining.push(candidate);
                } else {
                    newTableCards.push(candidate);
                }
            }
        }

        if (instantWinnerId) {
            set({
                deck: remaining,
                tableCards: newTableCards,
                players: updatedPlayers,
                phase: "finished",
                lastPlay: null,
                round: round + 1,
                currentTurn: null,
                winnerId: instantWinnerId,
            });
            return;
        }

        // The player AFTER the dealer starts the round
        const nonDealer =
            updatedPlayers.find((p) => p.id !== dealerId)?.id ??
            updatedPlayers[0].id;

        set({
            deck: remaining,
            tableCards: newTableCards,
            players: updatedPlayers,
            phase: "playing",
            lastPlay: null,
            round: round + 1,
            currentTurn: nonDealer,
        });
    },

    // ── playCard ──────────────────────────────────────────────────────────────
    playCard(playerId: string, card: Card): PointEvent[] {
        const state = get();
        const events: PointEvent[] = [];

        // --- Guards ---
        if (state.phase !== "playing") {
            throw new Error(
                `Cannot play a card during phase "${state.phase}".`,
            );
        }
        if (state.currentTurn !== playerId) {
            throw new Error(
                `It is not player "${playerId}"'s turn (current: "${state.currentTurn}").`,
            );
        }

        const playerIndex = state.players.findIndex((p) => p.id === playerId);
        if (playerIndex === -1) {
            throw new Error(`Player "${playerId}" is not part of this game.`);
        }

        const player = state.players[playerIndex];
        const cardInHand = player.hand.find((c) => c.id === card.id);
        if (!cardInHand) {
            throw new Error(
                `Player "${playerId}" does not hold card "${card.id}".`,
            );
        }

        // --- Caída check (before capture, so lastPlay.wentToTable is readable) ---
        const isCaida = checkCaida(card, state.lastPlay, playerId);
        if (isCaida && state.lastPlay) {
            events.push({ type: "caida", forPlayerId: playerId, cardValue: card.value });
        }

        // --- Capture calculation ---
        const { captured, tableAfter, isLimpieza } = calculateCapture(
            card,
            state.tableCards,
        );

        if (isLimpieza) {
            events.push({ type: "limpieza", forPlayerId: playerId });
        }

        // --- Apply points immediately so the caller can animate/notify ---
        const pointsEarned = events.reduce(
            (sum, ev) => sum + calculatePoints(ev),
            0,
        );

        // --- Remove card from hand ---
        const newHand = player.hand.filter((c) => c.id !== card.id);

        // --- Update captured pile ---
        const newCaptured = [...player.captured, ...captured];

        // --- Build updated player list ---
        const updatedPlayers = state.players.map((p, idx) => {
            if (idx === playerIndex) {
                return {
                    ...p,
                    hand: newHand,
                    captured: newCaptured,
                    score: p.score + pointsEarned,
                };
            }
            return p;
        });

        // --- Record last play ---
        const lastPlay: LastPlay = {
            playerId,
            card,
            wentToTable: captured.length === 0,
        };

        // --- Determine next turn ---
        const nextTurn = getNextTurn(playerId, updatedPlayers);

        // --- Check if all hands are empty ---
        const allHandsEmpty = updatedPlayers.every((p) => p.hand.length === 0);

        set({
            players: updatedPlayers,
            tableCards: tableAfter,
            lastPlay,
            currentTurn: allHandsEmpty ? null : nextTurn,
            phase: allHandsEmpty ? "scoring" : "playing",
        });

        // If all hands are empty, trigger scoring (next deal or game end)
        if (allHandsEmpty) {
            get().scoreRound();
        }

        return events;
    },

    // ── scoreRound ────────────────────────────────────────────────────────────
    scoreRound() {
        const { players, deck } = get();

        // Build a map: playerId → number of captured cards
        const captureMap = new Map<string, number>(
            players.map((p) => [p.id, p.captured.length]),
        );

        // Determine mayorCartas event
        const mayorEvents = resolveMayorCartas(captureMap);

        // Apply mayorCartas points
        let updatedPlayers = players.map((p) => {
            const ev = mayorEvents.find((e) => e.forPlayerId === p.id);
            if (!ev) return p;
            return { ...p, score: p.score + calculatePoints(ev) };
        });

        // Check win condition
        const scoreMap = new Map<string, number>(
            updatedPlayers.map((p) => [p.id, p.score]),
        );
        const winnerId = checkWinCondition(scoreMap);

        if (winnerId) {
            set({ players: updatedPlayers, phase: "finished", winnerId });
            return;
        }

        // --- More rounds to play? ---
        const cardsNeeded = players.length * 3;

        if (deck.length >= cardsNeeded) {
            // Reset hands for next deal (captured cards stay; cantos will be re-detected)
            updatedPlayers = updatedPlayers.map((p) => ({
                ...p,
                hand: [],
                cantos: [],
            }));
            set({ players: updatedPlayers, phase: "dealing" });
            get().dealRound();
        } else {
            // Reshuffle all captured cards back into a fresh deck and start over
            const newDeck = shuffleDeck(generateDeck());
            const currentDealerId = get().dealerId;
            const newDealerId =
                updatedPlayers.find((p) => p.id !== currentDealerId)?.id ??
                updatedPlayers[0].id;

            // Reset captured piles for a new hand, but preserve scores
            updatedPlayers = updatedPlayers.map((p) => ({
                ...p,
                hand: [],
                captured: [],
                cantos: [],
            }));

            set({
                players: updatedPlayers,
                deck: newDeck,
                phase: "dealing",
                round: 0,
                dealerId: newDealerId,
            });
            get().dealRound();
        }
    },

    // ── resetEngine ───────────────────────────────────────────────────────────
    resetEngine() {
        set(INITIAL_STATE);
    },
}));

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Returns the ID of the next player after `currentPlayerId` in round-robin order.
 * Falls back to the first player if the current player is last.
 */
function getNextTurn(currentPlayerId: string, players: EnginePlayer[]): string {
    const idx = players.findIndex((p) => p.id === currentPlayerId);
    const nextIdx = (idx + 1) % players.length;
    return players[nextIdx].id;
}
